### ISSUE TITLE
a problem of repmat

### ISSUE THREAD

**Issue by HongJinZ** [mortezamg63/Texture-Segmentation-using-Gabor-Filters#15]
Hello, I'm so lucky to download the file you provided. But when I run this code, an error has occurred. It is specifically like this：
The replication factor must be an integer row vector or an integer scalar.
复制因子必须为整数行矢量或整数标量。
imseg(idx, :) = repmat(color(i, :), [], length(idx));

**Comment by mortezamg63** [comment]
Hello, I could see the problem. But because I wrote the code long time ago, I could not understand the problem with function and I don't have currently enough time to spend time finding solution. But an alternative solution is this.
Please replace the following line of code with the line you mentioned. 
imseg(idx,:) = seg(idx).*color(i,:)

;)

**Comment by mortezamg63** [comment]
Pay attention to ".*" or dot product
